# config.yml
#run command: rqalpha run -d rqdata/bundle
base:
  data_bundle_path: ~
  # 启动的策略文件路径
  strategy_file: f_buy_and_hold.py
  # 回测起始日期
  start_date: 2015-06-01
  # 回测结束日期(如果是实盘，则忽略该配置)
  end_date: 2050-01-01
  # 股票起始资金，默认为0
  stock_starting_cash: 100000
  # 设置策略可交易品种，目前支持 `stock` (股票策略)、`future` (期货策略)
  securities: [stock]
  # 目前支持 `1d` (日线回测) 和 `1m` (分钟线回测)，如果要进行分钟线，请注意是否拥有对应的数据源，目前开源版本是不提供对应的数据源的。
  frequency: 1d
  # Benchmark，如果不设置，默认没有基准参照。
  benchmark:
extra:
  # 开启日志输出
  log_level: verbose
mod:
  sys_analyser:
    enabled: true
    # 开启 plot 功能
    plot: true